// ============================================================
// MUSEION — Données de démonstration Storyboard (Gilgamesh)
// 5 séquences, 22 scènes, plans techniques, assets, connexions.
// Toutes les vues consomment ces mêmes données via le store.
// ============================================================

import type {
  Asset,
  Sequence,
  Shot,
  ShotType,
  StoryboardEdge,
  StoryboardScene,
} from '@/lib/types-storyboard'
import { computeExpiry, MS_PER_DAY } from '@/lib/assetLifecycle'
import { buildMockPreviewDataUri } from '@/providers/preview/mockSvg'
import { MOCK_MODEL_NAME } from '@/providers/preview/MockPreviewProvider'

const PROJECT_ID = 'proj-gilgamesh'

export const DEMO_SEQUENCES: Sequence[] = [
  {
    id: 'seq-01',
    projectId: PROJECT_ID,
    number: 1,
    title: 'Le roi et le héros',
    description: 'Uruk sous le joug de Gilgamesh, la naissance d’Enkidu, la rencontre.',
    color: '#ececea',
    order: 0,
  },
  {
    id: 'seq-02',
    projectId: PROJECT_ID,
    number: 2,
    title: 'L’appel à l’aventure',
    description: 'La décision de partir affronter Humbaba, le refus des anciens, le départ.',
    color: '#c6c7c4',
    order: 1,
  },
  {
    id: 'seq-03',
    projectId: PROJECT_ID,
    number: 3,
    title: 'L’épreuve de la forêt',
    description: 'La Forêt des Cèdres, le rêve prémonitoire, Humbaba, la transgression.',
    color: '#a0a2a0',
    order: 2,
  },
  {
    id: 'seq-04',
    projectId: PROJECT_ID,
    number: 4,
    title: 'Le déluge',
    description: 'La colère d’Ishtar, la montée des eaux, la mort d’Enkidu.',
    color: '#7b7d7c',
    order: 3,
  },
  {
    id: 'seq-05',
    projectId: PROJECT_ID,
    number: 5,
    title: 'Retour à Uruk',
    description: 'La traversée, Utnapishtim, le retour au pied du mur.',
    color: '#5a5c5e',
    order: 4,
  },
  {
    id: 'seq-akh-01',
    projectId: 'proj-akhenaton',
    number: 1,
    title: 'Le culte du disque',
    description: "La cérémonie qui fonde le culte d'Aton, le doute du pharaon, les ruines du règne.",
    color: '#c9a15a',
    order: 0,
  },
  {
    id: 'seq-alex-01',
    projectId: 'proj-alexandre',
    number: 1,
    title: 'La conquête et le doute',
    description: "La charge qui ne s'arrête jamais, l'entrée dans Babylone, la nuit du général seul.",
    color: '#8a2f2f',
    order: 0,
  },
]

// ------------------------------------------------------------
// Scènes
// ------------------------------------------------------------

type SceneSeed = Omit<StoryboardScene, 'projectId' | 'canvasPosition' | 'order'>

const SCENE_SEEDS: SceneSeed[] = [
  // ---- Séquence 1 ----
  {
    id: 'sb-scene-01',
    sequenceId: 'seq-01',
    number: 1,
    title: 'Les murs d’Uruk',
    location: 'Ext. — Uruk, la muraille',
    timeOfDay: 'EXT',
    moment: 'Jour',
    emotion: 'Émerveillement, écrasement',
    intention: 'Établir Uruk, montrer l’ampleur et la grandeur.',
    description:
      'La caméra découvre la muraille de brique cuite. Des porteurs minuscules longent le chemin de ronde.',
    lighting: 'golden-backlight',
    duration: 8,
    mainShotType: 'extreme-wide',
    notes: 'Plan d’ouverture. Aucune coupe avant l’arrivée sur la porte principale.',
  },
  {
    id: 'sb-scene-02',
    sequenceId: 'seq-01',
    number: 2,
    title: 'Le roi sur son trône',
    location: 'Int. — Palais d’Uruk, salle du trône',
    timeOfDay: 'INT',
    moment: 'Jour',
    emotion: 'Orgueil, tension, défi',
    intention: 'Introduire Gilgamesh et son arrogance.',
    description:
      'Gilgamesh rejette les conseils de son conseiller et affirme son pouvoir absolu.',
    lighting: 'chiaroscuro',
    duration: 7,
    mainShotType: 'medium-close',
    notes: 'Le brasero reste hors champ. Une seule source visible.',
  },
  {
    id: 'sb-scene-03',
    sequenceId: 'seq-01',
    number: 3,
    title: 'La plainte du peuple',
    location: 'Ext. — Uruk, place du marché',
    timeOfDay: 'EXT',
    moment: 'Jour',
    emotion: 'Colère contenue, épuisement',
    intention: 'Illustrer l’oppression du peuple.',
    description: 'Les habitants d’Uruk se rassemblent et murmurent contre le roi.',
    lighting: 'natural-side',
    duration: 6,
    mainShotType: 'wide',
    notes: 'Foule réelle au premier plan, extension numérique interdite en V1.',
  },
  {
    id: 'sb-scene-04',
    sequenceId: 'seq-01',
    number: 4,
    title: 'La naissance d’Enkidu',
    location: 'Ext. — Plaine d’Uruk',
    timeOfDay: 'EXT',
    moment: 'Aube',
    emotion: 'Étrangeté, promesse',
    intention: 'Présenter Enkidu, l’égal de Gilgamesh.',
    description: 'Enkidu se relève de la glaise, entouré de bêtes qui ne le fuient pas.',
    lighting: 'diffuse',
    duration: 7,
    mainShotType: 'medium',
    notes: 'Aucun maquillage brillant : la peau doit rester mate.',
  },
  {
    id: 'sb-scene-05',
    sequenceId: 'seq-01',
    number: 5,
    title: 'Enkidu parmi les bêtes',
    location: 'Ext. — Plaine d’Uruk, points d’eau',
    timeOfDay: 'EXT',
    moment: 'Jour',
    emotion: 'Paix animale',
    intention: 'Montrer Enkidu en harmonie avec la nature.',
    description: 'Enkidu boit avec le troupeau. Aucun humain dans le cadre.',
    lighting: 'natural-side',
    duration: 6,
    mainShotType: 'wide',
    notes: 'Le troupeau doit être le même que celui de la scène 04.',
  },
  {
    id: 'sb-scene-06',
    sequenceId: 'seq-01',
    number: 6,
    title: 'Le combat',
    location: 'Int. — Palais d’Uruk, salle du trône',
    timeOfDay: 'INT',
    moment: 'Nuit',
    emotion: 'Rage, égalité',
    intention: 'Le combat entre Gilgamesh et Enkidu.',
    description:
      'Les deux corps s’affrontent jusqu’à l’épuisement. Aucun des deux ne l’emporte.',
    lighting: 'chiaroscuro',
    duration: 9,
    mainShotType: 'medium',
    notes: 'Cascade réglée : privilégier les plans larges pour éviter les doublures visibles.',
  },
  {
    id: 'sb-scene-07',
    sequenceId: 'seq-01',
    number: 7,
    title: 'L’amitié',
    location: 'Int. — Palais d’Uruk, salle du trône',
    timeOfDay: 'INT',
    moment: 'Nuit',
    emotion: 'Reconnaissance, soulagement',
    intention: 'Naissance d’une amitié profonde.',
    description: 'Les deux hommes rient au sol, épuisés. Le pouvoir vient de basculer.',
    lighting: 'chiaroscuro',
    duration: 6,
    mainShotType: 'close',
    notes: 'Aucun dialogue. Le son porte la scène.',
  },
  {
    id: 'sb-scene-08',
    sequenceId: 'seq-01',
    number: 8,
    title: 'La décision',
    location: 'Ext. — Uruk, terrasse haute',
    timeOfDay: 'EXT',
    moment: 'Crépuscule',
    emotion: 'Exaltation, inconscience',
    intention: 'Décision de partir à l’aventure ensemble.',
    description: 'Gilgamesh désigne l’horizon. Enkidu hésite, puis accepte.',
    lighting: 'golden-backlight',
    duration: 7,
    mainShotType: 'american',
    notes: 'Le geste vers l’horizon doit répondre au plan final du film.',
  },
  // ---- Séquence 2 ----
  {
    id: 'sb-scene-09',
    sequenceId: 'seq-02',
    number: 9,
    title: 'La forêt interdite',
    location: 'Ext. — Lisière de la Forêt des Cèdres',
    timeOfDay: 'EXT',
    moment: 'Crépuscule',
    emotion: 'Appréhension',
    intention: 'Nommer la menace : Humbaba.',
    description: 'La forêt apparaît au loin, immobile, comme un mur vivant.',
    lighting: 'golden-backlight',
    duration: 8,
    mainShotType: 'extreme-wide',
    notes: 'Aucune créature visible. La menace reste hors champ.',
  },
  {
    id: 'sb-scene-10',
    sequenceId: 'seq-02',
    number: 10,
    title: 'La forge',
    location: 'Int. — Palais d’Uruk, atelier',
    timeOfDay: 'INT',
    moment: 'Jour',
    emotion: 'Détermination',
    intention: 'Forger les armes du voyage.',
    description: 'Le métal en fusion, les haches, les sceaux gravés au nom du roi.',
    lighting: 'packshot-premium',
    duration: 6,
    mainShotType: 'insert',
    notes: 'Série d’inserts. Chaque objet doit être identifiable au dernier acte.',
  },
  {
    id: 'sb-scene-11',
    sequenceId: 'seq-02',
    number: 11,
    title: 'Le conseil des anciens',
    location: 'Int. — Palais d’Uruk, salle du trône',
    timeOfDay: 'INT',
    moment: 'Jour',
    emotion: 'Doute, autorité contestée',
    intention: 'Les anciens tentent de retenir le roi.',
    description: 'Les anciens rappellent la loi. Gilgamesh écoute et refuse.',
    lighting: 'window-interior',
    duration: 7,
    mainShotType: 'american',
    notes: 'Trois personnages tenus dans le même cadre, sans champ-contrechamp.',
  },
  {
    id: 'sb-scene-12',
    sequenceId: 'seq-02',
    number: 12,
    title: 'Le départ',
    location: 'Ext. — Uruk, porte principale',
    timeOfDay: 'EXT',
    moment: 'Aube',
    emotion: 'Élan, peur retenue',
    intention: 'Franchir la porte et quitter la cité.',
    description: 'La porte s’ouvre, les deux hommes sortent seuls. Personne ne les suit.',
    lighting: 'natural-side',
    duration: 9,
    mainShotType: 'wide',
    notes: 'Plan à raccorder avec le retour, séquence 5.',
  },
  // ---- Séquence 3 ----
  {
    id: 'sb-scene-13',
    sequenceId: 'seq-03',
    number: 13,
    title: 'Sous la canopée',
    location: 'Ext. — Forêt des Cèdres',
    timeOfDay: 'EXT',
    moment: 'Jour',
    emotion: 'Écrasement, respect',
    intention: 'Faire sentir la verticalité du monde ancien.',
    description: 'Les troncs montent hors cadre. La lumière descend en colonnes.',
    lighting: 'volumetric',
    duration: 8,
    mainShotType: 'extreme-wide',
    notes: 'Densité de brume mesurée à chaque prise.',
  },
  {
    id: 'sb-scene-14',
    sequenceId: 'seq-03',
    number: 14,
    title: 'Le rêve',
    location: 'Ext. — Forêt des Cèdres, campement',
    timeOfDay: 'EXT',
    moment: 'Nuit',
    emotion: 'Angoisse',
    intention: 'Annoncer l’affrontement par le rêve.',
    description: 'Gilgamesh se réveille en sursaut. Enkidu interprète le rêve.',
    lighting: 'chiaroscuro',
    duration: 7,
    mainShotType: 'close',
    notes: 'Aucune image de rêve montrée : uniquement le récit.',
  },
  {
    id: 'sb-scene-15',
    sequenceId: 'seq-03',
    number: 15,
    title: 'Humbaba',
    location: 'Ext. — Forêt des Cèdres, clairière',
    timeOfDay: 'EXT',
    moment: 'Jour',
    emotion: 'Terreur sacrée',
    intention: 'Révéler le gardien.',
    description: 'Un œil immense s’ouvre entre les troncs. Rien d’autre n’est montré.',
    lighting: 'volumetric',
    duration: 9,
    mainShotType: 'extreme-close',
    notes: 'La créature ne doit jamais être montrée en entier.',
  },
  {
    id: 'sb-scene-16',
    sequenceId: 'seq-03',
    number: 16,
    title: 'L’abattage du cèdre',
    location: 'Ext. — Forêt des Cèdres',
    timeOfDay: 'EXT',
    moment: 'Crépuscule',
    emotion: 'Transgression',
    intention: 'Montrer le prix de la victoire.',
    description: 'Le cèdre tombe. Le silence qui suit dure plus longtemps que la chute.',
    lighting: 'golden-backlight',
    duration: 8,
    mainShotType: 'medium',
    notes: 'Le son de la chute est coupé net : décision de montage actée.',
  },
  // ---- Séquence 4 ----
  {
    id: 'sb-scene-17',
    sequenceId: 'seq-04',
    number: 17,
    title: 'La colère d’Ishtar',
    location: 'Int. — Temple d’Ishtar',
    timeOfDay: 'INT',
    moment: 'Nuit',
    emotion: 'Humiliation, menace',
    intention: 'Le refus de Gilgamesh déclenche la catastrophe.',
    description: 'Ishtar offre, Gilgamesh refuse. La sentence tombe sans un cri.',
    lighting: 'chiaroscuro',
    duration: 7,
    mainShotType: 'medium-close',
    notes: 'Les voiles bougent d’ouest en est, comme dans toutes les scènes du temple.',
  },
  {
    id: 'sb-scene-18',
    sequenceId: 'seq-04',
    number: 18,
    title: 'La montée des eaux',
    location: 'Ext. — Euphrate, rive et déluge',
    timeOfDay: 'EXT',
    moment: 'Nuit',
    emotion: 'Panique',
    intention: 'Le fleuve nourricier devient destructeur.',
    description: 'Les digues cèdent. Les barques s’arrachent à leurs amarres.',
    lighting: 'night-ambient',
    duration: 10,
    mainShotType: 'wide',
    notes: 'Le niveau d’eau ne redescend jamais d’un plan à l’autre.',
  },
  {
    id: 'sb-scene-19',
    sequenceId: 'seq-04',
    number: 19,
    title: 'La mort d’Enkidu',
    location: 'Int. — Palais d’Uruk, chambre',
    timeOfDay: 'INT',
    moment: 'Aube',
    emotion: 'Effondrement',
    intention: 'Le premier deuil du roi.',
    description: 'Enkidu s’éteint lentement. Gilgamesh reste immobile, incapable d’agir.',
    lighting: 'window-interior',
    duration: 9,
    mainShotType: 'close',
    notes: 'Plan fixe unique. Aucune coupe pendant toute la scène.',
  },
  // ---- Séquence 5 ----
  {
    id: 'sb-scene-20',
    sequenceId: 'seq-05',
    number: 20,
    title: 'Les eaux de la mort',
    location: 'Ext. — Montagne de Mashu, tunnel',
    timeOfDay: 'EXT',
    moment: 'Nuit',
    emotion: 'Solitude',
    intention: 'Traverser le passage vers l’au-delà.',
    description: 'Une seule torche dans le noir absolu. Le pas résonne.',
    lighting: 'night-ambient',
    duration: 8,
    mainShotType: 'pov',
    notes: 'La torche est la seule source visible : aucun appoint autorisé.',
  },
  {
    id: 'sb-scene-21',
    sequenceId: 'seq-05',
    number: 21,
    title: 'Utnapishtim',
    location: 'Ext. — Marais d’Utnapishtim',
    timeOfDay: 'EXT',
    moment: 'Jour',
    emotion: 'Apaisement amer',
    intention: 'Recevoir la vérité sur la mort.',
    description: 'Le survivant du déluge parle sans se lever. L’eau ne bouge pas.',
    lighting: 'diffuse',
    duration: 7,
    mainShotType: 'medium',
    notes: 'Surface de l’eau strictement plane : aucun vent en machinerie.',
  },
  {
    id: 'sb-scene-22',
    sequenceId: 'seq-05',
    number: 22,
    title: 'Retour aux murs',
    location: 'Ext. — Uruk, la muraille',
    timeOfDay: 'EXT',
    moment: 'Crépuscule',
    emotion: 'Acceptation',
    intention: 'Boucler sur le mur : ce qui reste d’un homme.',
    description: 'Gilgamesh montre la muraille. Le geste répond à celui de la scène 08.',
    lighting: 'golden-backlight',
    duration: 9,
    mainShotType: 'extreme-wide',
    notes: 'Muraille ébréchée : état post-déluge obligatoire.',
  },
]

/** Disposition initiale du canvas : une ligne par séquence. */
export function defaultCanvasPosition(sequenceOrder: number, indexInSequence: number) {
  return { x: 80 + indexInSequence * 260, y: 80 + sequenceOrder * 220 }
}

export const DEMO_STORYBOARD_SCENES: StoryboardScene[] = SCENE_SEEDS.map((seed) => {
  const sequence = DEMO_SEQUENCES.find((s) => s.id === seed.sequenceId)!
  const siblings = SCENE_SEEDS.filter((s) => s.sequenceId === seed.sequenceId)
  const indexInSequence = siblings.findIndex((s) => s.id === seed.id)
  return {
    ...seed,
    projectId: PROJECT_ID,
    order: indexInSequence,
    canvasPosition: defaultCanvasPosition(sequence.order, indexInSequence),
  }
})

// ------------------------------------------------------------
// Plans techniques
// ------------------------------------------------------------

type ShotSeed = Omit<Shot, 'projectId' | 'order'>

const SHOT_SEEDS: ShotSeed[] = [
  {
    id: 'shot-001',
    sceneId: 'sb-scene-01',
    number: 1,
    type: 'wide',
    focal: '28 mm',
    camera: 'ARRI Alexa 35',
    sensor: 'Super 35 — ALEV 4',
    ratio: '2.39:1',
    movement: 'dolly-in',
    angle: 'Léger contre-plongée',
    height: '1,60 m',
    filter: 'ND 0.6 — Warm Pro-Mist 1/4',
    duration: 6.2,
    frameRate: 24,
    lighting: 'golden-backlight',
    decor: 'Ext. — Uruk, la muraille',
    continuity: 'Jour — 1er bloc',
    risks: 'Fenêtre de lumière dorée très courte : deux prises maximum par soir.',
    references: ['Relevés archéologiques d’Uruk-Warka'],
    notes:
      'Introduire Uruk et l’ampleur du royaume. Le mouvement avant doit rester lent et solennel. Personnages en silhouettes au premier plan.',
    validated: true,
  },
  {
    id: 'shot-002',
    sceneId: 'sb-scene-01',
    number: 2,
    type: 'extreme-wide',
    focal: '24 mm',
    camera: 'ARRI Alexa Mini LF',
    sensor: 'Grand format — ALEV III',
    ratio: '2.39:1',
    movement: 'crane',
    angle: 'Plongée',
    height: '12,00 m — grue haute',
    filter: 'ND 1.2',
    duration: 8,
    frameRate: 24,
    lighting: 'golden-backlight',
    decor: 'Ext. — Uruk, la muraille',
    continuity: 'Jour — 1er bloc',
    risks: 'Vent en haut de grue. Prévoir une fenêtre météo.',
    references: ['Ziggurat d’Ur'],
    notes: 'Descente de grue révélant la porte principale. Fin du plan sur la foule.',
    validated: false,
  },
  {
    id: 'shot-003',
    sceneId: 'sb-scene-02',
    number: 3,
    type: 'medium-close',
    focal: '85 mm',
    camera: 'ARRI Alexa 35',
    sensor: 'Super 35 — ALEV 4',
    ratio: '2.39:1',
    movement: 'push-in',
    angle: 'Niveau du regard',
    height: '1,60 m',
    filter: 'Black Pro-Mist 1/8',
    duration: 3.4,
    frameRate: 24,
    lighting: 'chiaroscuro',
    decor: 'Int. — Palais d’Uruk, salle du trône',
    continuity: 'Jour — 1er bloc',
    risks: 'Rapport de contraste élevé : surveiller les hautes lumières sur le front.',
    references: ['Mosaïques de cônes d’Uruk'],
    notes: 'Le visage sort de l’ombre au fil du push-in. Aucun fill frontal.',
    validated: true,
  },
  {
    id: 'shot-004',
    sceneId: 'sb-scene-02',
    number: 4,
    type: 'insert',
    focal: '100 mm macro',
    camera: 'ARRI Alexa 35',
    sensor: 'Super 35 — ALEV 4',
    ratio: '2.39:1',
    movement: 'static',
    angle: 'Plongée',
    height: '0,90 m — hauteur de table',
    filter: 'Aucun',
    duration: 2.5,
    frameRate: 24,
    lighting: 'packshot-premium',
    decor: 'Int. — Palais d’Uruk, salle du trône',
    continuity: 'Jour — 1er bloc',
    risks: 'Profondeur de champ de quelques millimètres.',
    references: ['Sceaux-cylindres du British Museum'],
    notes: 'Insert sur le sceau royal posé sur la tablette.',
    validated: false,
  },
  {
    id: 'shot-005',
    sceneId: 'sb-scene-03',
    number: 5,
    type: 'wide',
    focal: '35 mm',
    camera: 'Blackmagic URSA Cine 12K LF',
    sensor: 'Grand format RGBW',
    ratio: '2.39:1',
    movement: 'handheld',
    angle: 'Niveau du regard',
    height: '1,60 m',
    filter: 'ND 0.9',
    duration: 5.5,
    frameRate: 24,
    lighting: 'natural-side',
    decor: 'Ext. — Uruk, place du marché',
    continuity: 'Jour — 1er bloc',
    risks: 'Figuration nombreuse : prévoir un second assistant caméra.',
    references: ['Marchés de Bassorah'],
    notes: 'Caméra portée au milieu de la foule, sans stabilisation.',
    validated: false,
  },
  {
    id: 'shot-006',
    sceneId: 'sb-scene-06',
    number: 6,
    type: 'medium',
    focal: '40 mm',
    camera: 'RED V-RAPTOR 8K VV',
    sensor: 'Vista Vision',
    ratio: '2.39:1',
    movement: 'orbital',
    angle: 'Niveau du regard',
    height: '1,20 m — hauteur d’enfant',
    filter: 'Black Pro-Mist 1/4',
    duration: 7,
    frameRate: 48,
    lighting: 'chiaroscuro',
    decor: 'Int. — Palais d’Uruk, salle du trône',
    continuity: 'Nuit — 1er bloc',
    risks: 'Cascade : chorégraphie validée avant tournage, doublures visibles à éviter.',
    references: ['Combats au sol filmés en orbital'],
    notes: 'Orbital lent autour des deux corps enlacés au sol.',
    validated: true,
  },
  {
    id: 'shot-007',
    sceneId: 'sb-scene-06',
    number: 7,
    type: 'close',
    focal: '75 mm',
    camera: 'RED V-RAPTOR 8K VV',
    sensor: 'Vista Vision',
    ratio: '2.39:1',
    movement: 'handheld',
    angle: 'Contre-plongée',
    height: '0,30 m — au sol',
    filter: 'Black Pro-Mist 1/4',
    duration: 2.8,
    frameRate: 96,
    lighting: 'chiaroscuro',
    decor: 'Int. — Palais d’Uruk, salle du trône',
    continuity: 'Nuit — 1er bloc',
    risks: 'Ralenti à 96 i/s : besoin de lumière supplémentaire.',
    references: [],
    notes: 'Gros plan sur la main d’Enkidu qui lâche prise.',
    validated: false,
  },
  {
    id: 'shot-008',
    sceneId: 'sb-scene-12',
    number: 8,
    type: 'wide',
    focal: '32 mm',
    camera: 'ARRI Alexa Mini LF',
    sensor: 'Grand format — ALEV III',
    ratio: '2.39:1',
    movement: 'steadicam',
    angle: 'Niveau du regard',
    height: '1,60 m',
    filter: 'ND 0.6',
    duration: 9,
    frameRate: 24,
    lighting: 'natural-side',
    decor: 'Ext. — Uruk, porte principale',
    continuity: 'Aube — 2e bloc',
    risks: 'Aube courte. Répétition obligatoire la veille.',
    references: ['Porte d’Ishtar de Babylone (palette uniquement)'],
    notes: 'Steadicam suivant les deux hommes du seuil jusqu’à la plaine.',
    validated: true,
  },
  {
    id: 'shot-009',
    sceneId: 'sb-scene-13',
    number: 9,
    type: 'extreme-wide',
    focal: '21 mm',
    camera: 'ARRI Alexa Mini LF',
    sensor: 'Grand format — ALEV III',
    ratio: '2.39:1',
    movement: 'tilt',
    angle: 'Contre-plongée',
    height: '0,30 m — au sol',
    filter: 'Warm Pro-Mist 1/2',
    duration: 8,
    frameRate: 24,
    lighting: 'volumetric',
    decor: 'Ext. — Forêt des Cèdres',
    continuity: 'Jour — 3e bloc',
    risks: 'Atmosphérique en extérieur : densité instable selon le vent.',
    references: ['Cédraies du Chouf'],
    notes: 'Tilt du sol jusqu’à la canopée. Les faisceaux doivent rester lisibles.',
    validated: false,
  },
  {
    id: 'shot-010',
    sceneId: 'sb-scene-15',
    number: 10,
    type: 'extreme-close',
    focal: '135 mm',
    camera: 'ARRI Alexa 35',
    sensor: 'Super 35 — ALEV 4',
    ratio: '2.39:1',
    movement: 'static',
    angle: 'Niveau du regard',
    height: '1,80 m — au-dessus du regard',
    filter: 'Aucun',
    duration: 4,
    frameRate: 24,
    lighting: 'volumetric',
    decor: 'Ext. — Forêt des Cèdres, clairière',
    continuity: 'Jour — 3e bloc',
    risks: 'Effet pratique de l’œil : prototype à valider en essai.',
    references: [],
    notes: 'L’œil d’Humbaba occupe tout le cadre. La créature n’est jamais montrée entière.',
    validated: false,
  },
  {
    id: 'shot-011',
    sceneId: 'sb-scene-18',
    number: 11,
    type: 'wide',
    focal: '29 mm',
    camera: 'Sony VENICE 2',
    sensor: 'Plein format 8,6K',
    ratio: '2.39:1',
    movement: 'dolly-lateral',
    angle: 'Légère plongée',
    height: '3,00 m — surélevée',
    filter: 'ND interne 1.2',
    duration: 10,
    frameRate: 24,
    lighting: 'night-ambient',
    decor: 'Ext. — Euphrate, rive et déluge',
    continuity: 'Nuit — 4e bloc',
    risks: 'Tournage en eau : sécurité plateau prioritaire, matériel étanche obligatoire.',
    references: ['Crues du Tigre documentées'],
    notes: 'Travelling latéral longeant la digue qui cède.',
    validated: false,
  },
  {
    id: 'shot-012',
    sceneId: 'sb-scene-19',
    number: 12,
    type: 'close',
    focal: '65 mm',
    camera: 'Sony VENICE 2',
    sensor: 'Plein format 8,6K',
    ratio: '2.39:1',
    movement: 'static',
    angle: 'Niveau du regard',
    height: '0,90 m — hauteur de table',
    filter: 'Black Pro-Mist 1/8',
    duration: 9,
    frameRate: 24,
    lighting: 'window-interior',
    decor: 'Int. — Palais d’Uruk, chambre',
    continuity: 'Aube — 4e bloc',
    risks: 'Plan unique sans coupe : la lumière doit tenir 9 secondes exactement.',
    references: [],
    notes: 'Plan fixe sur le visage d’Enkidu. Aucune coupe pendant toute la scène.',
    validated: true,
  },
  {
    id: 'shot-013',
    sceneId: 'sb-scene-22',
    number: 13,
    type: 'extreme-wide',
    focal: '24 mm',
    camera: 'ARRI Alexa Mini LF',
    sensor: 'Grand format — ALEV III',
    ratio: '2.39:1',
    movement: 'pull-out',
    angle: 'Niveau du regard',
    height: '1,60 m',
    filter: 'ND 0.6 — Warm Pro-Mist',
    duration: 9,
    frameRate: 24,
    lighting: 'golden-backlight',
    decor: 'Ext. — Uruk, la muraille',
    continuity: 'Crépuscule — 5e bloc',
    risks: 'Muraille ébréchée : décor post-déluge à ne pas confondre avec le bloc 1.',
    references: ['Relevés archéologiques d’Uruk-Warka'],
    notes: 'Pull-out final. Le geste vers le mur répond à la scène 08.',
    validated: true,
  },
]

export const DEMO_SHOTS: Shot[] = SHOT_SEEDS.map((seed, index) => ({
  ...seed,
  projectId: PROJECT_ID,
  order: index,
}))

// ------------------------------------------------------------
// Connexions du tableau dynamique
// ------------------------------------------------------------

function buildSequentialEdges(): StoryboardEdge[] {
  const edges: StoryboardEdge[] = []
  for (let i = 0; i < DEMO_STORYBOARD_SCENES.length - 1; i++) {
    const current = DEMO_STORYBOARD_SCENES[i]
    const next = DEMO_STORYBOARD_SCENES[i + 1]
    if (current.sequenceId !== next.sequenceId) continue
    edges.push({
      id: `edge-${current.id}-${next.id}`,
      source: current.id,
      target: next.id,
      type: 'sequential',
    })
  }
  return edges
}

export const DEMO_STORYBOARD_EDGES: StoryboardEdge[] = [
  ...buildSequentialEdges(),
  // Raccords entre séquences
  { id: 'edge-seq1-seq2', source: 'sb-scene-08', target: 'sb-scene-09', type: 'sequential' },
  { id: 'edge-seq2-seq3', source: 'sb-scene-12', target: 'sb-scene-13', type: 'sequential' },
  { id: 'edge-seq3-seq4', source: 'sb-scene-16', target: 'sb-scene-17', type: 'sequential' },
  { id: 'edge-seq4-seq5', source: 'sb-scene-19', target: 'sb-scene-20', type: 'sequential' },
  // Branche alternative envisagée au montage
  {
    id: 'edge-alt-01',
    source: 'sb-scene-08',
    target: 'sb-scene-12',
    type: 'alternative',
    label: 'Montage court — sans le conseil',
  },
]

// ------------------------------------------------------------
// Assets
// ------------------------------------------------------------

const NOW = Date.now()

function iso(offsetDays: number): string {
  return new Date(NOW - offsetDays * MS_PER_DAY).toISOString()
}

interface AssetSeed {
  id: string
  name: string
  type: Asset['type']
  status: Asset['status']
  createdDaysAgo: number
  sceneId?: string
  subject: string
  location: string
  intention: string
  shotType: ShotType
  lighting: string
  prompt: string
}

const ASSET_SEEDS: AssetSeed[] = [
  {
    id: 'asset-ref-uruk',
    name: 'Référence — Muraille d’Uruk',
    type: 'reference',
    status: 'canonical',
    createdDaysAgo: 40,
    subject: 'Muraille de brique cuite, tours régulières',
    location: 'Ext. — Uruk, la muraille',
    intention: 'Fixer l’échelle du décor principal',
    shotType: 'extreme-wide',
    lighting: 'golden-backlight',
    prompt: 'Muraille d’Uruk, contre-jour doré, échelle monumentale',
  },
  {
    id: 'asset-ref-throne',
    name: 'Référence — Salle du trône',
    type: 'decor',
    status: 'canonical',
    createdDaysAgo: 38,
    subject: 'Salle longitudinale, piliers à mosaïque de cônes',
    location: 'Int. — Palais d’Uruk, salle du trône',
    intention: 'Fixer la lumière du pouvoir',
    shotType: 'wide',
    lighting: 'chiaroscuro',
    prompt: 'Salle du trône d’Uruk, clair-obscur, une seule source',
  },
  {
    id: 'asset-char-gilgamesh',
    name: 'Personnage — Gilgamesh',
    type: 'character',
    status: 'approved',
    createdDaysAgo: 30,
    subject: 'Gilgamesh, roi d’Uruk, barbe tressée, épaules larges',
    location: 'Int. — Palais d’Uruk, salle du trône',
    intention: 'Valider la silhouette du roi',
    shotType: 'medium-close',
    lighting: 'chiaroscuro',
    prompt: 'Gilgamesh en plan rapproché, clair-obscur, orgueil',
  },
  {
    id: 'asset-char-enkidu',
    name: 'Personnage — Enkidu',
    type: 'character',
    status: 'approved',
    createdDaysAgo: 29,
    subject: 'Enkidu, homme sauvage, cheveux longs, peau mate',
    location: 'Ext. — Plaine d’Uruk',
    intention: 'Valider la silhouette d’Enkidu',
    shotType: 'medium',
    lighting: 'diffuse',
    prompt: 'Enkidu en plan moyen, lumière diffuse, altérité',
  },
  {
    id: 'asset-decor-forest',
    name: 'Décor — Forêt des Cèdres',
    type: 'decor',
    status: 'approved',
    createdDaysAgo: 22,
    subject: 'Colonnade de troncs, faisceaux de lumière',
    location: 'Ext. — Forêt des Cèdres',
    intention: 'Fixer la verticalité du décor',
    shotType: 'extreme-wide',
    lighting: 'volumetric',
    prompt: 'Forêt des Cèdres, lumière volumétrique, verticalité',
  },
  {
    id: 'asset-scene-01',
    name: 'Storyboard — Scène 01',
    type: 'image',
    status: 'approved',
    createdDaysAgo: 12,
    sceneId: 'sb-scene-01',
    subject: 'Les murs d’Uruk — Établir Uruk, montrer l’ampleur',
    location: 'Ext. — Uruk, la muraille',
    intention: 'Établir Uruk, montrer l’ampleur et la grandeur.',
    shotType: 'extreme-wide',
    lighting: 'golden-backlight',
    prompt: 'Les murs d’Uruk, plan très large, contre-jour doré',
  },
  {
    id: 'asset-scene-02',
    name: 'Storyboard — Scène 02',
    type: 'image',
    status: 'approved',
    createdDaysAgo: 11,
    sceneId: 'sb-scene-02',
    subject: 'Le roi sur son trône — arrogance',
    location: 'Int. — Palais d’Uruk, salle du trône',
    intention: 'Introduire Gilgamesh et son arrogance.',
    shotType: 'medium-close',
    lighting: 'chiaroscuro',
    prompt: 'Gilgamesh sur son trône, clair-obscur, plan rapproché',
  },
  {
    id: 'asset-tmp-flood',
    name: 'Esquisse temporaire — Montée des eaux',
    type: 'image',
    status: 'ephemeral',
    createdDaysAgo: 12,
    sceneId: 'sb-scene-18',
    subject: 'Digues qui cèdent, barques arrachées',
    location: 'Ext. — Euphrate, rive et déluge',
    intention: 'Le fleuve nourricier devient destructeur.',
    shotType: 'wide',
    lighting: 'night-ambient',
    prompt: 'Montée des eaux, nuit, panique, plan large',
  },
  {
    id: 'asset-tmp-humbaba',
    name: 'Esquisse temporaire — Humbaba',
    type: 'image',
    status: 'ephemeral',
    createdDaysAgo: 3,
    subject: 'Œil immense entre les troncs',
    location: 'Ext. — Forêt des Cèdres, clairière',
    intention: 'Révéler le gardien.',
    shotType: 'extreme-close',
    lighting: 'volumetric',
    prompt: 'Œil d’Humbaba, très gros plan, lumière volumétrique',
  },
  {
    id: 'asset-tmp-mashu',
    name: 'Esquisse temporaire — Tunnel de Mashu',
    type: 'image',
    status: 'ephemeral',
    createdDaysAgo: 1,
    subject: 'Torche unique dans le noir',
    location: 'Ext. — Montagne de Mashu, tunnel',
    intention: 'Traverser le passage vers l’au-delà.',
    shotType: 'pov',
    lighting: 'night-ambient',
    prompt: 'Tunnel de Mashu, POV, torche unique',
  },
  {
    id: 'asset-scene-05',
    name: 'Storyboard — Scène 05',
    type: 'image',
    status: 'approved',
    createdDaysAgo: 10,
    sceneId: 'sb-scene-05',
    subject: 'Enkidu parmi les bêtes',
    location: 'Ext. — Plaine sauvage',
    intention: 'La vie sauvage avant la civilisation.',
    shotType: 'wide',
    lighting: 'golden-backlight',
    prompt: 'Enkidu dans la plaine, animaux sauvages, lumière dorée',
  },
  {
    id: 'asset-scene-06',
    name: 'Storyboard — Scène 06',
    type: 'image',
    status: 'approved',
    createdDaysAgo: 10,
    sceneId: 'sb-scene-06',
    subject: 'Le combat des titans',
    location: 'Ext. — Uruk, place publique',
    intention: 'L\'affrontement physique qui scelle leur amitié.',
    shotType: 'medium-close',
    lighting: 'daylight',
    prompt: 'Gilgamesh et Enkidu luttant, poussière, foule autour',
  },
  {
    id: 'asset-scene-15',
    name: 'Storyboard — Scène 15',
    type: 'image',
    status: 'approved',
    createdDaysAgo: 8,
    sceneId: 'sb-scene-15',
    subject: 'L\'affrontement contre Humbaba',
    location: 'Ext. — Forêt des Cèdres',
    intention: 'Le premier grand exploit.',
    shotType: 'wide',
    lighting: 'volumetric',
    prompt: 'Combat contre Humbaba, forêt dense, action',
  },
  {
    id: 'asset-scene-17',
    name: 'Storyboard — Scène 17',
    type: 'image',
    status: 'approved',
    createdDaysAgo: 7,
    sceneId: 'sb-scene-17',
    subject: 'La colère d\'Ishtar',
    location: 'Ext. — Uruk, les murs',
    intention: 'Le taureau céleste ravageant la ville.',
    shotType: 'wide',
    lighting: 'dramatic',
    prompt: 'Taureau géant furieux, poussière, Gilgamesh et Enkidu armés',
  },
  {
    id: 'asset-scene-19',
    name: 'Storyboard — Scène 19',
    type: 'image',
    status: 'approved',
    createdDaysAgo: 6,
    sceneId: 'sb-scene-19',
    subject: 'La mort d\'Enkidu',
    location: 'Int. — Palais d\'Uruk',
    intention: 'Le chagrin de Gilgamesh, la perte.',
    shotType: 'medium',
    lighting: 'chiaroscuro',
    prompt: 'Gilgamesh tenant Enkidu mourant, sombre, tragique',
  },
  {
    id: 'asset-scene-20',
    name: 'Storyboard — Scène 20',
    type: 'image',
    status: 'approved',
    createdDaysAgo: 5,
    sceneId: 'sb-scene-20',
    subject: 'Les eaux de la mort',
    location: 'Ext. — Rivière',
    intention: 'La solitude de la quête de l\'immortalité.',
    shotType: 'wide',
    lighting: 'overcast',
    prompt: 'Gilgamesh seul sur une barque, brume, eaux sombres',
  },
  {
    id: 'asset-scene-21',
    name: 'Storyboard — Scène 21',
    type: 'image',
    status: 'approved',
    createdDaysAgo: 4,
    sceneId: 'sb-scene-21',
    subject: 'Le serpent et la plante',
    location: 'Ext. — Point d\'eau',
    intention: 'La perte définitive de la jeunesse éternelle.',
    shotType: 'medium-close',
    lighting: 'golden-backlight',
    prompt: 'Serpent volant une plante magique, Gilgamesh agenouillé',
  },
  {
    id: 'asset-scene-22',
    name: 'Storyboard — Scène 22',
    type: 'image',
    status: 'approved',
    createdDaysAgo: 3,
    sceneId: 'sb-scene-22',
    subject: 'Le retour aux murs',
    location: 'Ext. — Murs d\'Uruk',
    intention: 'La sagesse trouvée dans l\'accomplissement mortel.',
    shotType: 'wide',
    lighting: 'sunrise',
    prompt: 'Vieux Gilgamesh contemplant Uruk au coucher du soleil',
  },
  {
    id: 'asset-decor-uruk-glory',
    name: 'Décor — Uruk la Grande',
    type: 'decor',
    status: 'canonical',
    createdDaysAgo: 42,
    subject: 'Panorama de la ville, Ziggourat au fond',
    location: 'Ext. — Uruk',
    intention: 'Établir la grandeur de la civilisation sumérienne.',
    shotType: 'extreme-wide',
    lighting: 'sunrise',
    prompt: 'Panorama d\'Uruk antique, Ziggourat, lever de soleil',
  }
]

const REAL_IMAGES: Record<string, string> = {
  'asset-char-gilgamesh': '/demo-gilgamesh/gilgamesh-char.jpg',
  'asset-char-enkidu': '/demo-gilgamesh/enkidu-char.jpg',
  'asset-decor-forest': '/demo-gilgamesh/scene-forest.jpg',
  'asset-scene-01': '/demo-gilgamesh/scene-01.jpg',
  'asset-scene-02': '/demo-gilgamesh/scene-02.jpg',
  'asset-tmp-flood': '/demo-gilgamesh/scene-flood.jpg',
  'asset-tmp-humbaba': '/demo-gilgamesh/scene-humbaba.jpg',
  'asset-tmp-mashu': '/demo-gilgamesh/scene-mashu.jpg',
  'asset-scene-05': '/demo-gilgamesh/scene-steppe.png',
  'asset-scene-06': '/demo-gilgamesh/scene-fight.png',
  'asset-scene-15': '/demo-gilgamesh/scene-humbaba-fight.png',
  'asset-scene-17': '/demo-gilgamesh/scene-bull.png',
  'asset-scene-19': '/demo-gilgamesh/scene-death.png',
  'asset-scene-20': '/demo-gilgamesh/scene-boat.png',
  'asset-scene-21': '/demo-gilgamesh/scene-snake.png',
  'asset-scene-22': '/demo-gilgamesh/scene-uruk-return.png',
  'asset-decor-uruk-glory': '/demo-gilgamesh/scene-uruk-glory.png',
}

const DEMO_ASSETS_GILGAMESH: Asset[] = ASSET_SEEDS.map((seed) => {
  const createdAt = iso(seed.createdDaysAgo)
  const url = REAL_IMAGES[seed.id] || buildMockPreviewDataUri({
    subject: seed.subject,
    location: seed.location,
    intention: seed.intention,
    shotType: seed.shotType,
    lighting: seed.lighting,
    seed: seed.id,
  })
  return {
    id: seed.id,
    projectId: PROJECT_ID,
    name: seed.name,
    type: seed.type,
    status: seed.status,
    url,
    prompt: seed.prompt,
    simulatedModel: MOCK_MODEL_NAME,
    sceneId: seed.sceneId,
    createdAt,
    expiresAt: seed.status === 'ephemeral' ? computeExpiry(createdAt) : undefined,
    approvedAt: seed.status === 'approved' || seed.status === 'canonical' ? createdAt : undefined,
    approvedBy:
      seed.status === 'approved' || seed.status === 'canonical' ? 'Administrateur' : undefined,
    metadata: {
      'Type de plan': seed.shotType,
      Lumière: seed.lighting,
      Lieu: seed.location,
    },
    versions: [],
    relations: [],
  }
})

/** Rattache les miniatures validées à leurs scènes. */
const DEMO_GILGAMESH_SCENES_WITH_ASSETS: StoryboardScene[] = DEMO_STORYBOARD_SCENES.map((scene) => {
  const asset = DEMO_ASSETS_GILGAMESH.find((a) => a.sceneId === scene.id && a.status !== 'ephemeral')
  return asset ? { ...scene, assetId: asset.id } : scene
})

// ------------------------------------------------------------
// Storyboards secondaires — Akhenaton, Alexandre
//
// Trois scènes chacun, construites à partir des images fournies
// (public/demo-akhenaton, public/demo-alexandre). Pas encore de plans
// techniques ni de connexions : ces deux projets n'ont pas de découpage
// validé, contrairement à Gilgamesh.
// ------------------------------------------------------------

const SECONDARY_ASSETS: Asset[] = [
  {
    id: 'asset-akh-ceremony',
    projectId: 'proj-akhenaton',
    name: 'Storyboard — La cérémonie du disque',
    type: 'image',
    status: 'approved',
    url: '/demo-akhenaton/scene-ceremony.png',
    sceneId: 'sb-scene-akh-01',
    createdAt: iso(20),
    approvedAt: iso(20),
    approvedBy: 'Administrateur',
    metadata: { 'Type de plan': 'wide', Lumière: 'volumetric', Lieu: "Grand temple d'Aton, Akhetaton" },
    versions: [],
    relations: [],
  },
  {
    id: 'asset-akh-atendisk',
    projectId: 'proj-akhenaton',
    name: 'Storyboard — Face au disque solaire',
    type: 'image',
    status: 'approved',
    url: '/demo-akhenaton/scene-aten-disk.png',
    sceneId: 'sb-scene-akh-02',
    createdAt: iso(18),
    approvedAt: iso(18),
    approvedBy: 'Administrateur',
    metadata: { 'Type de plan': 'medium', Lumière: 'chiaroscuro', Lieu: 'Sanctuaire du temple' },
    versions: [],
    relations: [],
  },
  {
    id: 'asset-akh-templeruin',
    projectId: 'proj-akhenaton',
    name: 'Storyboard — Les ruines du culte',
    type: 'image',
    status: 'approved',
    url: '/demo-akhenaton/scene-temple-ruin.png',
    sceneId: 'sb-scene-akh-03',
    createdAt: iso(15),
    approvedAt: iso(15),
    approvedBy: 'Administrateur',
    metadata: { 'Type de plan': 'extreme-wide', Lumière: 'volumetric', Lieu: "Temple d'Aton, en ruines" },
    versions: [],
    relations: [],
  },
  {
    id: 'asset-alex-army',
    projectId: 'proj-alexandre',
    name: 'Storyboard — La charge',
    type: 'image',
    status: 'approved',
    url: '/demo-alexandre/scene-army.png',
    sceneId: 'sb-scene-alex-01',
    createdAt: iso(14),
    approvedAt: iso(14),
    approvedBy: 'Administrateur',
    metadata: { 'Type de plan': 'medium-close', Lumière: 'dramatic', Lieu: 'Plaine de bataille' },
    versions: [],
    relations: [],
  },
  {
    id: 'asset-alex-babylon',
    projectId: 'proj-alexandre',
    name: "Storyboard — L'entrée dans Babylone",
    type: 'image',
    status: 'approved',
    url: '/demo-alexandre/scene-babylon.png',
    sceneId: 'sb-scene-alex-02',
    createdAt: iso(12),
    approvedAt: iso(12),
    approvedBy: 'Administrateur',
    metadata: { 'Type de plan': 'wide', Lumière: 'golden-backlight', Lieu: 'Porte de Babylone' },
    versions: [],
    relations: [],
  },
  {
    id: 'asset-alex-balcony',
    projectId: 'proj-alexandre',
    name: 'Storyboard — Seul face à la carte',
    type: 'image',
    status: 'approved',
    url: '/demo-alexandre/scene-balcony.png',
    sceneId: 'sb-scene-alex-03',
    createdAt: iso(9),
    approvedAt: iso(9),
    approvedBy: 'Administrateur',
    metadata: { 'Type de plan': 'medium', Lumière: 'night-ambient', Lieu: 'Terrasse du palais, Babylone' },
    versions: [],
    relations: [],
  },
]

const SECONDARY_SCENES: StoryboardScene[] = [
  {
    id: 'sb-scene-akh-01',
    sequenceId: 'seq-akh-01',
    projectId: 'proj-akhenaton',
    number: 1,
    title: 'La cérémonie du disque',
    location: "Int. — Grand temple d'Aton, Akhetaton",
    timeOfDay: 'INT',
    moment: 'Jour',
    emotion: 'Ferveur, autorité',
    intention: "Akhenaton et Néfertiti instaurent publiquement le culte d'un dieu unique.",
    description: 'Le couple royal traverse la nef du temple sous un rayon de lumière, entouré de prêtres et du peuple.',
    lighting: 'volumetric',
    duration: 10,
    mainShotType: 'wide',
    assetId: 'asset-akh-ceremony',
    order: 0,
    canvasPosition: defaultCanvasPosition(0, 0),
    notes: '',
  },
  {
    id: 'sb-scene-akh-02',
    sequenceId: 'seq-akh-01',
    projectId: 'proj-akhenaton',
    number: 2,
    title: 'Face au disque solaire',
    location: 'Int. — Sanctuaire du temple',
    timeOfDay: 'INT',
    moment: 'Jour',
    emotion: 'Doute, solitude',
    intention: "Seul face à la lumière d'Aton, Akhenaton commence à douter de son propre culte.",
    description: "Akhenaton s'avance seul vers le puits de lumière ; Néfertiti l'observe de loin, en retrait.",
    lighting: 'chiaroscuro',
    duration: 8,
    mainShotType: 'medium',
    assetId: 'asset-akh-atendisk',
    order: 1,
    canvasPosition: defaultCanvasPosition(0, 1),
    notes: '',
  },
  {
    id: 'sb-scene-akh-03',
    sequenceId: 'seq-akh-01',
    projectId: 'proj-akhenaton',
    number: 3,
    title: 'Les ruines du culte',
    location: "Int. — Temple d'Aton, en ruines",
    timeOfDay: 'INT',
    moment: 'Jour',
    emotion: 'Perte, héritage brisé',
    intention: "Après la chute d'Akhenaton, un enfant contemple la statue brisée du pharaon hérétique.",
    description: "Un enfant se tient seul devant la statue colossale et fracturée d'Akhenaton, seul vestige du culte aboli.",
    lighting: 'volumetric',
    duration: 8,
    mainShotType: 'extreme-wide',
    assetId: 'asset-akh-templeruin',
    order: 2,
    canvasPosition: defaultCanvasPosition(0, 2),
    notes: '',
  },
  {
    id: 'sb-scene-alex-01',
    sequenceId: 'seq-alex-01',
    projectId: 'proj-alexandre',
    number: 1,
    title: 'La charge',
    location: 'Ext. — Plaine de bataille',
    timeOfDay: 'EXT',
    moment: 'Aube',
    emotion: 'Élan, fureur',
    intention: "Alexandre entraîne sa cavalerie dans une nouvelle charge, incapable de s'arrêter.",
    description: 'Alexandre, épée levée, mène sa cavalerie macédonienne à travers la poussière et les étendards.',
    lighting: 'dramatic',
    duration: 6,
    mainShotType: 'medium-close',
    assetId: 'asset-alex-army',
    order: 0,
    canvasPosition: defaultCanvasPosition(0, 0),
    notes: '',
  },
  {
    id: 'sb-scene-alex-02',
    sequenceId: 'seq-alex-01',
    projectId: 'proj-alexandre',
    number: 2,
    title: "L'entrée dans Babylone",
    location: 'Ext. — Porte de Babylone',
    timeOfDay: 'EXT',
    moment: 'Jour',
    emotion: 'Triomphe sans joie',
    intention: "Alexandre entre en conquérant dans Babylone, un triomphe de plus qui ne le comble plus.",
    description: "De dos, à cheval, Alexandre franchit la grande porte de la ville sous les acclamations de la foule.",
    lighting: 'golden-backlight',
    duration: 10,
    mainShotType: 'wide',
    assetId: 'asset-alex-babylon',
    order: 1,
    canvasPosition: defaultCanvasPosition(0, 1),
    notes: '',
  },
  {
    id: 'sb-scene-alex-03',
    sequenceId: 'seq-alex-01',
    projectId: 'proj-alexandre',
    number: 3,
    title: 'Seul face à la carte',
    location: 'Int/Ext. — Terrasse du palais, Babylone',
    timeOfDay: 'EXT',
    moment: 'Nuit',
    emotion: 'Doute, épuisement',
    intention: "Pour la première fois, Alexandre se demande pourquoi il avance encore.",
    description: 'Alexandre, seul sur une terrasse dominant la ville illuminée, regarde une carte sans la voir.',
    lighting: 'night-ambient',
    duration: 8,
    mainShotType: 'medium',
    assetId: 'asset-alex-balcony',
    order: 2,
    canvasPosition: defaultCanvasPosition(0, 2),
    notes: '',
  },
]

export const DEMO_ASSETS: Asset[] = [...DEMO_ASSETS_GILGAMESH, ...SECONDARY_ASSETS]

export const DEMO_SCENES_WITH_ASSETS: StoryboardScene[] = [
  ...DEMO_GILGAMESH_SCENES_WITH_ASSETS,
  ...SECONDARY_SCENES,
]
